### ISSUE TITLE
Support netstandard

### ISSUE THREAD

**Issue by damianh** [damianh/OwinHttpMessageHandler#13]

**Comment by StefanOssendorf** [comment]
Hey damian,

I've ported this lib as far as I can.
https://github.com/StefanOssendorf/OwinHttpMessageHandler

There are two failing/missing tests (Nowin & HttpListener).
Tried to replace HttpListener with WebListener but with no success.

The sample Project is broken but I can't figure out why. My refence looks fine but the compiler says the type is still missing.

**Comment by damianh** [comment]
@StefanOssendorf ok, will look this when the tooling is in a better place.

**Comment by jchannon** [comment]
pfft, jump in the water is lovely.

tbh the tooling is fine imo

**Comment by jchannon** [comment]
See #18

**Comment by damianh** [comment]
> tbh the tooling is fine imo

hehe

**Comment by damianh** [comment]
This is in progress.

**Comment by damianh** [comment]
Done. Nearly 2 years from whence the issue was created. What a journey :)
