### ISSUE TITLE
Setting server.User

### ISSUE THREAD

**Issue by Jonne** [damianh/OwinHttpMessageHandler#14]
Not really an Issue, but if you are using this with Web API and are decorating your actions with the Authorize attribute, you need to set the user:

new OwinHttpMessageHandler(next =>
                {
                    AppFunc setUser = async environment =>
                    {
                        environment["server.User"] = Thread.CurrentPrincipal;

                        // Call the next Middleware in the chain:
                        await appFunc.Invoke(environment);
                    };

                    return setUser;
                })

The issue tracker is probably not the place for this, but might be useful to add this to the wiki.

Hopefully this will safe someone some time.

**Comment by damianh** [comment]
Thx for mentioning this here, issue tracker is fine :)

How are you doing your authentication? For me, I typically have authentication / security middleware as part of my pipeline-under-test. So I "login" using httpclient using standard HTTP mechanisms i.e. send a form post with a user name password & retain the cookie for subsequent requests or use `Authorization` header.

For readability, I'll also create an extension method over `HttpClient` that I use in my tests to encapsulate this. i.e. "await client.LoginAs(user, pass);". Usually, you'll want to set `UseCookies=true;` on `OwinHttpMessageHandler`.

But if you don't have security MW as part of your SUT, then yes you need set the user in the pipeline yourself, between the `AppFunc/MidFunc` under test and the `OwinHttpMessageHandler`, as you have done above.

Couple of things to note:
 1. Next version of owin uses `owin.RequestUser` as the enviroment key; so you'll need to set both for compatibility. https://github.com/owin/owin/issues/9
 2. Using `Thread.CurrentPrincipal` is considered harmful. New up a `ClaimsPrincipal` instance instead.

#### Example:
```
var claimsPrincipal = new ClaimsPrincipal();
var handler = new OwinHttpMessageHandler(next => env =>
{
    env["server.User"] = claimsPrincipal;
    env["owin.RequestUser"] = claimsPrincipal;
    return next(env);
});
```

**Comment by Jonne** [comment]
In our case we are integrating with a CMS and want to use the same authentication mechanism, so we depend on classic forms authentication. 

Thanks for the notes, appreciate it and will change it.

**Comment by damianh** [comment]
Ah ok. 

This means you'll be mixing the owin pipeline in with the classic aspnet pipeline. You'll need to check the order in which stuff runs. If the owin stuff executes first, the  classic aspnet auth handler will not have run, extracted the user from the auth cookie and set the Thread.CurrentPrincipal. If so you'll need some MW to decrypt and extract the aspnet auth cookie.
