### ISSUE TITLE
Is this doing the same thing as my package?

### ISSUE THREAD

**Issue by cottsak** [damianh/OwinHttpMessageHandler#17]
https://github.com/cottsak/ControllerTests/blob/master/ControllerTests/ApiControllerTestBase.cs

**Comment by damianh** [comment]
Similar concept except OwinHttpMessageHandler works with much more than just WebApi. It's a lib that you use to connect to a pipeline, no inheritance required. It's also dependency free ;)

**Comment by cottsak** [comment]
What do you mean "to a pipeline"? I was under the understanding that post-MVC6, only Web Api2 had a "pipeline" that one could use like this. 

Or do you mean "pipeline" in the OWIN sense? Can you explain that a little more for me please? Does this mean it works with `Controller` and `ApiController` on MVC5?

**Comment by damianh** [comment]
Yes, an owin pipeline. This sample should describe it: https://github.com/damianh/OwinHttpMessageHandler/blob/master/src/Samples/TestingMsOwinStartup.cs

Asp.Net MVC (or anything System.Web based) cannot be hosted in an owin pipeline.

WebAPI, Nancy, SignalR and other frameworks than _can_ be hosted in an owin pipeline can be tested with this.
