### ISSUE TITLE
Request Headers are not preserved on redirects

### ISSUE THREAD

**Issue by nukefusion** [damianh/OwinHttpMessageHandler#20]
I've got a client configured with DefaultRequestHeaders (accept, etc, not authorization headers). It looks like a new request is being created for redirects and the headers are not being copied across.

**Comment by damianh** [comment]
I think you are right https://github.com/damianh/OwinHttpMessageHandler/blob/master/src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs#L188

@nukefusion could I interest you in sending a PR?

**Comment by damianh** [comment]
`v1.3.6` on nuget.org.

Thanks for the PR :)
